paularmstrong/onerepo

- cli.md
- plugins/vitest/docs/cli.md
- plugins/vitest/package.json
- plugins/vitest/src/commands/vitest.ts
- yarn.lock
- ndb is no longer maintained
- Fixes arguments for vitest
> fix: plugin-vitest

- docs/package.json
- internal/eslint-plugin/src/index.cjs
- modules/cli/src/functions/git.ts
- modules/cli/src/functions/subprocess.ts
- modules/graph/src/Repository.ts
- modules/logger/src/index.ts
- modules/test-cli/src/index.ts
- plugins/docgen/src/yargs.ts
- plugins/install/src/commands/install.ts
- plugins/tasks/src/commands/tasks.test.ts
- yarn.lock
**Problem:** Astro wouldn't run.
**Solution:** Fix dependencies. there was magic in thar be dragons
> fix: eslint config

- modules/test-cli/src/index.ts
- plugins/install/src/commands/install.test.ts
- plugins/install/src/commands/install.ts
> feat(plugin-install): run husky install if husky is found

- .changeset/real-garlics-laugh.md
- bin/one.cjs
- config/graph-schema.ts
- docs/src/pages/docs/contributing/cli.md
- internal/tsconfig/package.json
- modules/cli/src/index.ts
- plugins/docgen/package.json
- plugins/graph/docs/index.md
- plugins/graph/package.json
- plugins/graph/src/commands/verify.ts
- plugins/graph/src/index.ts
- plugins/graph/src/schema.ts
- plugins/install/src/index.ts
- plugins/tasks/src/index.ts
- yarn.lock
Extendable to validate any other JSON file in workspaces using AJV
> feat(plugin-graph): add json schema validation for package.json

- .changeset/hip-students-speak.md
- .eslintignore
- .prettierignore
- plugins/prettier/src/commands/prettier.test.ts
- plugins/prettier/src/commands/prettier.ts
> feat(plugin-prettier): respect prettierignore before passing files through

- bin/one.cjs
- docs/src/pages/docs/contributing/cli.md
- modules/git/src/index.ts
- modules/test-cli/src/index.ts
- modules/types/src/index.ts
- modules/yargs/src/getters.ts
- modules/yargs/src/yargs.ts
- plugins/tasks/README.md
- plugins/tasks/src/commands/tasks.test.ts
- plugins/tasks/src/commands/tasks.ts
- plugins/tasks/src/index.ts
> fix(plugin-tasks): ensure ignores is respected

- .changeset/giant-swans-share.md
- config/templates/module/.onegen.cjs
- modules/core/docs/generate.md
- modules/core/src/core/generate/commands/__fixtures__/module/.onegen.cjs
- modules/core/src/core/generate/commands/generate.test.ts
- modules/core/src/core/generate/commands/generate.ts
- modules/core/src/core/generate/index.ts
> Add inquirer prompts to the 'generate' command config

- internal/eslint-plugin/package.json
- internal/eslint-plugin/src/index.cjs
- yarn.lock
> chore: remove eslint-plugin-react from internal config

- yarn.lock
> chore: update eslint

- modules/core/src/deps.d.ts
- yarn.lock
Dependabot won't pick up changes from the dependabot.yml file for the current open PRs, so this is doing it manually.
> chore: update dependencies

- .changeset/metal-poets-push.md
- config/graph-schema.ts
- config/templates/module/package.json.ejs
- config/templates/plugin/package.json.ejs
- modules/builders/package.json
- modules/core/package.json
- modules/file/package.json
- modules/git/package.json
- modules/graph/package.json
- modules/logger/package.json
- modules/onerepo/package.json
- modules/subprocess/package.json
- modules/test-cli/package.json
- modules/yargs/package.json
- plugins/changesets/package.json
- plugins/docgen/package.json
- plugins/eslint/package.json
- plugins/prettier/package.json
- plugins/typescript/package.json
- plugins/vitest/package.json
> fix: ensure dist files included is recursive

- .changeset/rude-pugs-learn.md
- bin/one.cjs
- commands/build.ts
- docs/commands/collect-content.ts
- docs/commands/typedoc.ts
- docs/package.json
- modules/core/commands/docgen.ts
- modules/core/package.json
- modules/core/src/core/generate/commands/generate.ts
- modules/core/src/core/graph/commands/verify.ts
- modules/graph/package.json
- modules/graph/src/Graph.ts
- package.json
- plugins/docgen/package.json
- plugins/docgen/src/yargs.ts
- yarn.lock
> chore: update to glob@9

- .changeset/gold-bikes-grin.md
- modules/core/src/workspaces.ts
> fix(core): prevent --help from failing when run from workspace

- .changeset/curly-mirrors-suffer.md
- modules/core/src/index.ts
> fix(core): bring completions back

- .changeset/grumpy-tools-knock.md
- .changeset/metal-cherries-shop.md
- modules/core/src/core/generate/commands/__fixtures__/app/.test
- modules/core/src/core/generate/commands/generate.test.ts
- modules/core/src/core/generate/commands/generate.ts
- Support optional `nameFormat` and `dirnameFormat` for generate config
- Support dotfiles when running generate
> Dotfiles and optional config params

- .changeset/eighty-apricots-sort.md
- .changeset/healthy-plums-clap.md
- .changeset/tame-weeks-appear.md
- modules/core/src/core/generate/commands/generate.test.ts
- modules/core/src/core/generate/commands/generate.ts
- modules/package-manager/src/__tests__/npm.test.ts
- modules/package-manager/src/__tests__/pnpm.test.ts
- modules/package-manager/src/__tests__/yarn.test.ts
- modules/package-manager/src/methods.ts
- modules/package-manager/src/npm.ts
- modules/package-manager/src/pnpm.ts
- modules/package-manager/src/yarn.ts
- modules/test-cli/src/index.ts
- plugins/changesets/src/commands/__tests__/version.test.ts
- plugins/changesets/src/commands/version.ts
> Run install and update lockfiles when necessary.

- docs/package.json
- modules/core/package.json
- modules/graph/package.json
- modules/logger/package.json
- modules/onerepo/package.json
- modules/package-manager/package.json
- modules/test-cli/package.json
- package.json
- plugins/changesets/package.json
- plugins/docgen/package.json
- plugins/eslint/package.json
- plugins/jest/package.json
- plugins/prettier/package.json
- plugins/vitest/package.json
- yarn.lock
Seems to be okay not throwing any errors.
> chore: update to typescript 5

- .changeset/smooth-adults-itch.md
- config/templates/command/.onegen.js
- config/templates/module/.onegen.cjs
- config/templates/plugin/.onegen.js
- modules/core/src/core/generate/README.md
- modules/core/src/core/generate/commands/__tests__/__fixtures__/module/.onegen.cjs
- modules/core/src/core/generate/commands/__tests__/generate.test.ts
- modules/core/src/core/generate/commands/generate.ts
> feat(core): add name/desc options to generate templates

- .changeset/curvy-toys-check.md
- plugins/changesets/src/commands/add.ts
- plugins/changesets/src/commands/prerelease.ts
- plugins/changesets/src/commands/version.ts
**Problem:** Changesets (upstream packages) do not implement ESM correctly. Related: https://github.com/changesets/changesets/issues/622
**Solution:** Hack around it for now.
> fix(changesets): changeset package broken

- .changeset/cold-grapes-bathe.md
- config/graph-schema.ts
- modules/core/src/core/graph/README.md
- modules/core/src/core/graph/commands/verify.ts
- modules/core/src/core/graph/schema.ts
> feat(core): allow `graph verify` to require files exist via schema extension

- .changeset/plenty-socks-sip.md
- modules/onerepo/src/setup/setup.ts
- modules/onerepo/tsconfig.build.json
- modules/onerepo/tsconfig.json
- modules/yargs/src/yargs.ts
> feat: add version number flag

- .changeset/fresh-buses-hope.md
- .github/CODEOWNERS
- modules/file/src/index.ts
- modules/graph/package.json
- modules/graph/src/Workspace.ts
- modules/graph/src/__tests__/__fixtures__/reused-alias/onerepo.config.js
- modules/onerepo/package.json
- modules/onerepo/src/core/codeowners/README.md
- modules/onerepo/src/core/codeowners/commands/__tests__/__fixtures__/repo/modules/burritos/onerepo.config.js
- modules/onerepo/src/core/codeowners/commands/__tests__/__fixtures__/repo/modules/burritos/package.json
- modules/onerepo/src/core/codeowners/commands/__tests__/__fixtures__/repo/modules/tacos/onerepo.config.js
- modules/onerepo/src/core/codeowners/commands/__tests__/__fixtures__/repo/modules/tacos/package.json
- modules/onerepo/src/core/codeowners/commands/__tests__/__fixtures__/repo/onerepo.config.js
- modules/onerepo/src/core/codeowners/commands/__tests__/__fixtures__/repo/package.json
- modules/onerepo/src/core/codeowners/commands/__tests__/sync.test.ts
- modules/onerepo/src/core/codeowners/commands/__tests__/verify.test.ts
- modules/onerepo/src/core/codeowners/commands/sync.ts
- modules/onerepo/src/core/codeowners/commands/verify.ts
- modules/onerepo/src/core/codeowners/get-codeowners.ts
- modules/onerepo/src/core/codeowners/index.ts
- modules/onerepo/src/core/generate/README.md
- modules/onerepo/src/setup/index.ts
- modules/onerepo/src/setup/setup.ts
- modules/onerepo/src/types.ts
- onerepo.config.ts
- yarn.lock
> feat(core): add codeowners management

- .changeset/rude-ladybugs-unite.md
- modules/logger/src/Logger.ts
> feat(logger): warn when closing unfinished steps

- .changeset/serious-ducks-vanish.md
- plugins/changesets/src/commands/add.ts
- plugins/changesets/src/commands/version.ts
**Problem:**
Was attempting to version and publish oneRepo, but got an error running `one change version`.
**Solution:**
Changesets still has some broken issues with respect to ESM vs CJS and registering jiti fixes it.
Fixes #
**Checklist:**
> fix(changesets): jiti for add & version

- README.md
- docs/src/content/docs/changelogs/index.mdx
- docs/src/content/docs/concepts/why-onerepo.mdx
- docs/src/content/docs/core/dependencies.mdx
- docs/src/content/docs/core/generate.mdx
- docs/src/content/docs/core/graph.mdx
- docs/src/content/docs/core/install.mdx
- docs/src/content/docs/core/tasks.mdx
- docs/src/content/docs/docs/commands.mdx
- docs/src/content/docs/index.mdx
- docs/src/content/docs/plugins/docgen/example.mdx
- docs/src/content/docs/plugins/jest.mdx
- internal/prettier-config/src/index.cjs
**Problem:**
The documentation for writing commands was not fully fleshed out.
**Solution:**
Add a short tutorial and more.
Fixes #
**Checklist:**
> docs: flesh out 'writing commands'

- modules/onerepo/.changes/014-small-lines-fix.md
- modules/onerepo/src/core/changes/verify.ts
- modules/onerepo/src/core/graph/__tests__/show.test.ts
- modules/onerepo/src/core/hooks/__tests__/index.test.ts
- modules/onerepo/src/core/tasks/__tests__/__fixtures__/repo/modules/burritos/onerepo.config.js
- modules/onerepo/src/core/tasks/__tests__/__fixtures__/repo/modules/tacos/onerepo.config.js
- modules/onerepo/src/core/tasks/__tests__/__fixtures__/repo/onerepo.config.js
- modules/onerepo/src/core/tasks/__tests__/tasks.test.ts
- modules/onerepo/src/core/tasks/run-tasks.ts
- modules/onerepo/src/core/tasks/tasks.ts
- onerepo.config.ts
- plugins/changesets/src/commands/__tests__/prerelease.test.ts
**Problem:**
Can't run `one change verify` in tasks locally…
**Solution:**
Ensure it's available in the `tasks` core command. Fixes tests. Runs all in CI.
> fix(tasks): add 'changes' to available core plugins

- modules/onerepo/.changes/018-wild-ghosts-attend.md
- modules/onerepo/src/core/changes/__tests__/version.test.ts
- modules/onerepo/src/core/changes/utils/__tests__/apply-versions.test.ts
- modules/onerepo/src/core/changes/utils/__tests__/changelog.test.ts
- modules/onerepo/src/core/changes/utils/__tests__/read-change.test.ts
- modules/onerepo/src/core/changes/utils/changelog.ts
- modules/onerepo/src/core/changes/utils/get-versionable.ts
- modules/onerepo/src/core/changes/utils/read-change.ts
- modules/onerepo/src/core/changes/version.ts
**Problem:**
I tried to version, but the change entry files were not removed.
**Solution:**
Ensure they're removed.
> fix(core): ensure change entries are _consumed_

- plugins/docgen/.changes/001-forty-cities-pull.md
- plugins/docgen/package.json
- plugins/docgen/src/index.ts
- plugins/docgen/src/yargs.ts
- plugins/eslint/.changes/004-forty-cities-pull.md
- plugins/eslint/package.json
- plugins/eslint/src/commands/__tests__/eslint.test.ts
- plugins/eslint/src/commands/eslint.ts
- plugins/jest/.changes/003-forty-cities-pull.md
- plugins/jest/package.json
- plugins/jest/src/commands/__tests__/jest.test.ts
- plugins/jest/src/commands/jest.ts
- plugins/performance-writer/.changes/000-forty-cities-pull.md
- plugins/performance-writer/package.json
- plugins/performance-writer/src/__tests__/index.test.ts
- plugins/performance-writer/src/index.ts
- plugins/prettier/.changes/003-forty-cities-pull.md
- plugins/prettier/package.json
- plugins/prettier/src/commands/__tests__/prettier.test.ts
- plugins/prettier/src/commands/prettier.ts
- plugins/typescript/.changes/002-forty-cities-pull.md
- plugins/typescript/package.json
- plugins/typescript/src/commands/__tests__/typescript.test.ts
- plugins/typescript/src/commands/typescript.ts
- plugins/vitest/.changes/003-forty-cities-pull.md
- plugins/vitest/package.json
- plugins/vitest/src/commands/__tests__/vitest.test.ts
- plugins/vitest/src/commands/vitest.ts
- yarn.lock
Avoids duplicates being installed going forward when using plugins
> chore: update plugin internal dependencies

- docs/src/content/docs/concepts/primer.mdx
- docs/src/content/docs/plugins/vitest.mdx
- modules/graph/.changes/000-wide-humans-act.md
- modules/graph/src/__tests__/__fixtures__/pnpm/pnpm-workspace.yaml
- modules/graph/src/index.ts
- modules/onerepo/.changes/000-wide-humans-act.md
- modules/onerepo/src/core/create/create.ts
🤦🏻‍♂️ https://pnpm.io/pnpm-workspace_yaml
> fix(graph): pnpm-workspace.yaml is a thing

- docs/src/content/docs/core/generate.mdx
- docs/src/content/docs/plugins/docgen/example.mdx
- modules/onerepo/.changes/000-wild-eels-kiss.md
- modules/onerepo/src/core/generate/index.ts
**Problem:**
The URL in the `--help` output for `one generate` is incorrect
**Solution:**
Update the URL
> fix(core): generate help url

- docs/src/content/docs/api/index.md
- docs/src/content/docs/core/graph.mdx
- docs/src/content/docs/plugins/docgen/example.mdx
- modules/graph/.changes/001-clean-planets-shop.md
- modules/graph/src/Graph.ts
- modules/onerepo/.changes/003-clean-planets-shop.md
- modules/onerepo/src/core/changes/__tests__/add.test.ts
- modules/onerepo/src/core/graph/show.ts
- modules/onerepo/src/types/plugin.ts
> fix: capitalize Graph

- docs/src/content/docs/api/index.md
- docs/src/content/docs/core/generate.mdx
- docs/src/content/docs/docs/config.mdx
- docs/src/content/docs/plugins/docgen/example.mdx
- modules/onerepo/.changes/001-small-steaks-sin.md
- modules/onerepo/src/core/generate/generate.ts
- modules/onerepo/src/core/generate/index.ts
- modules/onerepo/src/types/config-root.ts
> docs: fix generate templatesDir

- docs/src/content/docs/core/changes.mdx
- docs/src/content/docs/core/graph.mdx
- docs/src/content/docs/docs/source-dependencies.mdx
- docs/src/content/docs/plugins/docgen/example.mdx
- docs/src/content/docs/plugins/typescript.mdx
- modules/onerepo/.changes/000-strong-walls-give.md
- modules/onerepo/src/core/changes/publish.ts
- modules/onerepo/src/core/changes/snapshot.ts
- modules/onerepo/src/core/changes/version.ts
- plugins/typescript/.changes/000-wide-clowns-enjoy.md
- plugins/typescript/src/index.ts
Some documentation improvements from when I was evaluating `oneRepo`. Please, feel free to commit on top of my changes or overwrite them!
> Fix typos, invalid examples, clarify

- internal/jest-config/package.json
- modules/builders/.changes/001-silly-foxes-marry.md
- modules/eslint-formatter/.changes/001-silly-foxes-marry.md
- modules/file/.changes/002-silly-foxes-marry.md
- modules/git/.changes/001-silly-foxes-marry.md
- modules/graph/.changes/002-silly-foxes-marry.md
- modules/logger/.changes/001-silly-foxes-marry.md
- modules/onerepo/.changes/002-silly-foxes-marry.md
- modules/package-manager/.changes/001-silly-foxes-marry.md
- modules/subprocess/.changes/001-silly-foxes-marry.md
- modules/test-cli/.changes/001-silly-foxes-marry.md
- modules/yargs/.changes/001-silly-foxes-marry.md
- package.json
- plugins/docgen/.changes/002-silly-foxes-marry.md
- plugins/eslint/.changes/002-silly-foxes-marry.md
- plugins/jest/.changes/001-silly-foxes-marry.md
- plugins/performance-writer/.changes/001-silly-foxes-marry.md
- plugins/prettier/.changes/001-silly-foxes-marry.md
- plugins/typescript/.changes/001-silly-foxes-marry.md
- plugins/vitest/.changes/001-silly-foxes-marry.md
- yarn.lock
**Problem:**
esbuild is out of date.
**Solution:**
Update
Replaces #752
> chore: update esbuild

- internal/jest-config/package.json
- internal/jest-config/src/globals.js
- internal/jest-config/src/index.js
- package.json
- yarn.lock
> chore: upgrade jest to v30
