- .changeset/sweet-hotels-beam.md
- modules/file/src/index.ts
- modules/test-cli/src/fixtures/repo/modules/burritos/package.json
- modules/test-cli/src/fixtures/repo/modules/tacos/package.json
- plugins/eslint/package.json
- plugins/eslint/src/commands/eslint.test.ts
- plugins/eslint/src/commands/eslint.ts
- yarn.lock
* Switches to use cache-strategy=content (should allow shared cache in CI)
* Adds lstat to file helpers
* Fixes potential issue with `--add` that could have been adding too many files
fixes #58
> feat(plugin-eslint): respect eslintignore

- .changeset/tidy-eggs-unite.md
- modules/git/src/index.ts
- plugins/changesets/src/commands/add.ts
To determine modified files, typically we want both the committed and uncommitted state.
> fix(git plugin-changesets): merge committed and uncommitted changes

- .changeset/honest-cameras-divide.md
- modules/graph/src/Workspace.ts
- plugins/tasks/README.md
- plugins/tasks/src/commands/__fixtures__/repo/modules/burritos/onerepo.config.js
- plugins/tasks/src/commands/tasks.test.ts
- plugins/tasks/src/commands/tasks.ts
Have found some cases where it will be helpful to add some meta information to the tasks run (like during deploy to configure environments, etc and the command is not part of the `one` command system). This should allow arbitrary information to be passed through for utilizing separately, like in GitHub action matrices.
> add task meta handling

- .changeset/orange-wasps-prove.md
- plugins/changesets/src/commands/__fixtures__/interconnected/.changeset/baz-bop-qux.md
- plugins/changesets/src/commands/__fixtures__/interconnected/.changeset/config.json
- plugins/changesets/src/commands/__fixtures__/interconnected/.changeset/foo-bar-baz.md
- plugins/changesets/src/commands/__fixtures__/interconnected/modules/burritos/package.json
- plugins/changesets/src/commands/__fixtures__/interconnected/modules/churros/package.json
- plugins/changesets/src/commands/__fixtures__/interconnected/modules/tacos/package.json
- plugins/changesets/src/commands/__fixtures__/interconnected/modules/tortillas/package.json
- plugins/changesets/src/commands/__fixtures__/interconnected/package.json
- plugins/changesets/src/commands/version.test.ts
- plugins/changesets/src/commands/version.ts
**Problem:** When selecting workspaces for versioning, other packages were being versioned based on only the changesets related to the selected workspaces. This isn't quite right when there's a single changeset that spans multiple workspaces where one or more of those workspaces is not part of the list of workspaces originally requested to be versioned. This results in incorrectly versioning those extra workspaces and not including all of their changesets in changelogs.
**Solution:** Check for the extra workspaces, prompt that it will be necessary to included them, then do so if okay to proceed. Exit early and fail if not okay.
> fix(plugin-changesets): prompt for workspaces included in changesets

- .changeset/config.json
- config/templates/module/.onegen.cjs
- config/templates/module/src/index.ts.ejs
- internal/changeset-changelog/package.json
- internal/changeset-changelog/src/index.test.ts
- internal/changeset-changelog/src/index.ts
- internal/changeset-changelog/tsconfig.json
- internal/eslint-plugin/src/index.cjs
- yarn.lock
**Problem:** The default changesets changelog formatter has a weird behavior where it shows multiple update dependencies lines. It's a bit weird. For example:
```md
- Updated dependencies [c1863ba]
- Updated dependencies [6665501]
- Updated dependencies [2f4e19e]
- Updated dependencies [d502f2e]
- Updated dependencies [831ea55]
- Updated dependencies [6431e8d]
- Updated dependencies [65a63cf]
- Updated dependencies [831ea55]
- Updated dependencies [2f4e19e]
- Updated dependencies [2f4e19e]
- Updated dependencies [587b442]
- Updated dependencies [1293372]
- Updated dependencies [4f7433d]
- Updated dependencies [126c514]
- Updated dependencies [04c28b2]
- Updated dependencies [c7ffeaa]
- Updated dependencies [0a3bb03]
- Updated dependencies [65a63cf]
- Updated dependencies [65a63cf]
- …
```
> add internal changeset-changelog formatter

- .changeset/cuddly-dryers-confess.md
- modules/subprocess/src/index.ts
eg, for oneRepo itself running `one tsc` across all workspaces:
| Before | After | 
| --- | --- |
| [1m27s](https://github.com/paularmstrong/onerepo/actions/runs/4345466037/jobs/7590257407) | [47s](https://github.com/paularmstrong/onerepo/actions/runs/4348637980/jobs/7597441160) |
> feat: use both cpus when cpus.length === 2 in batch()

- .changeset/olive-rings-carry.md
- modules/graph/src/Graph.test.ts
- modules/graph/src/Graph.ts
- modules/graph/src/fixtures/reused-alias/modules/lettuce/package.json
- modules/graph/src/fixtures/reused-alias/modules/spinach/package.json
- modules/graph/src/fixtures/reused-alias/package.json
> fix: prevent workspaces from using the same aliases

- .changeset/eight-lies-dress.md
- config/graph-schema.ts
- modules/core/src/core/graph/commands/__tests__/__fixtures__/bad-repo/apps/menu/package.json
- modules/core/src/core/graph/commands/__tests__/__fixtures__/bad-repo/modules/burritos/package.json
- modules/core/src/core/graph/commands/__tests__/__fixtures__/bad-repo/modules/tacos/package.json
- modules/core/src/core/graph/commands/__tests__/__fixtures__/bad-repo/package.json
- modules/core/src/core/graph/commands/__tests__/verify.test.ts
- modules/core/src/core/graph/commands/verify.ts
- modules/core/src/core/graph/index.ts
**Problem:** The output of the `graph verify` command is not clear for what file is throwing each error
**Solution:** Make it clearer.
> fix(core): graph verify more clearly indicates file errors

- .changeset/lovely-seas-smile.md
- internal/eslint-plugin/src/index.cjs
- modules/core/src/core/graph/commands/__tests__/__fixtures__/bad-repo-dev/apps/menu/package.json
- modules/core/src/core/graph/commands/__tests__/__fixtures__/bad-repo-dev/modules/burritos/package.json
- modules/core/src/core/graph/commands/__tests__/__fixtures__/bad-repo-dev/modules/tacos/package.json
- modules/core/src/core/graph/commands/__tests__/__fixtures__/bad-repo-dev/package.json
- modules/core/src/core/graph/commands/__tests__/verify.test.ts
- modules/core/src/core/graph/commands/verify.ts
- modules/graph/src/Graph.ts
- modules/yargs/package.json
- yarn.lock
**Problem:** Errors were not being thrown when running `graph verify` and `dev` and `peer` dependencies were mismatched.
**Solution:** Ensure we include dev and peer dependencies in verification checks. Makes errors logged clearer to indicate _which_ workspace caught the error.
> fix(core): graph verify to check dev and peer dependencies

- .changeset/shiny-pets-run.md
- modules/package-manager/src/__tests__/npm.test.ts
- modules/package-manager/src/__tests__/pnpm.test.ts
- modules/package-manager/src/__tests__/yarn.test.ts
- modules/package-manager/src/npm.ts
- modules/package-manager/src/pnpm.ts
- modules/package-manager/src/yarn.ts
This should more accurately determine what needs to be published by selecting all workspaces, then removing those that have been published, instead of building up a set individually from the responses.
> fix(package-manager): publishable check to resist errors

- .changeset/sharp-paws-switch.md
- .changeset/yellow-bees-suffer.md
- modules/graph/src/Graph.ts
- modules/graph/src/__tests__/Graph.test.ts
- modules/graph/src/__tests__/__fixtures__/repo/modules/burritos/package.json
- modules/graph/src/__tests__/__fixtures__/repo/modules/lettuce/package.json
- modules/graph/src/__tests__/__fixtures__/repo/modules/tacos/package.json
- plugins/changesets/README.md
- plugins/changesets/src/commands/__tests__/__fixtures__/repo/.changeset/guh-gaz-gop.md
- plugins/changesets/src/commands/__tests__/__fixtures__/repo/modules/tacos/package.json
- plugins/changesets/src/commands/__tests__/__fixtures__/repo/modules/tortas/package.json
- plugins/changesets/src/commands/__tests__/prerelease.test.ts
- plugins/changesets/src/commands/__tests__/publish.test.ts
- plugins/changesets/src/commands/__tests__/version.test.ts
- plugins/changesets/src/commands/version.ts
**Problem:** When running `change version`, all dependencies, even `devDependencies` are being versioned and published. This is unexpected and unnecessary because `devDependencies` are explicitly filtered out of the `package.json` files when publishing.
**Solution:**
1. Add prod & dev graphs to the internal `Graph`
2. Add the ability to filter `dependents`, `dependencies`, `affected` and `isolatedGraph`s to the `DependencyType`
3. Filter dependencies during `change version` using the aforementioned filter abilities
4. Add tests
5. Add documentation caveats
Fixes #239
> fix(changsets): filter versioning dependencies to prod-only

- .changeset/odd-files-talk.md
- .changeset/slimy-hornets-relate.md
- .changeset/tasty-crabs-wave.md
- modules/core/src/core/install/commands/install.ts
- modules/file/src/__tests__/index.test.ts
- modules/file/src/index.ts
- modules/subprocess/src/index.ts
**Problem:** Completions are breaking after running `one install` multiple times in a row
On first run:
```sh
_one_yargs_completions()
{
local reply
local si=$IFS
IFS=$'
' reply=($(COMP_CWORD="$((CURRENT-1))" COMP_LINE="$BUFFER" COMP_POINT="$CURSOR" one --get-yargs-completions "${words[@]}"))
IFS=$si
_describe 'values' reply
}
```
On second run (see line 5)
```sh
_one_yargs_completions()
{
local reply
local si=$IFS
IFS= # <- missing `$'` here!
' reply=($(COMP_CWORD="$((CURRENT-1))" COMP_LINE="$BUFFER" COMP_POINT="$CURSOR" one --get-yargs-completions "${words[@]}"))
IFS=$si
_describe 'values' reply
}
```
**Solution:** `file.writeSafe` using `replace` was not writing out string literals, so regex substitutions like `$'` were getting replaced and not written correctly. By passing a function …
> fix(file): apply substitutions in writeSafe as string literals

- .changeset/tough-ducks-cheer.md
- plugins/prettier/package.json
- plugins/prettier/src/commands/__tests__/prettier.test.ts
- plugins/prettier/src/commands/prettier.ts
- plugins/prettier/src/index.ts
- yarn.lock
**Problem:** When prettier fails (with `--check`), just the list of files that fail formatting are listed with no other context.
**Solution:**
1. Add a clear error message with instructions on how to fix
2. In GitHub actions, annotate the files and include instructions on how to fix
> feat(prettier): clearer output on prettier errors

- .changeset/gentle-knives-report.md
- .changeset/modern-squids-tell.md
- .changeset/ninety-balloons-cry.md
- modules/eslint-formatter/package.json
- modules/eslint-formatter/src/index.js
- modules/eslint-formatter/tsconfig.build.json
- modules/eslint-formatter/tsconfig.json
- modules/subprocess/src/index.ts
- plugins/eslint/package.json
- plugins/eslint/src/commands/__tests__/eslint.test.ts
- plugins/eslint/src/commands/eslint.ts
- plugins/eslint/src/index.ts
- plugins/prettier/src/commands/prettier.ts
- plugins/prettier/src/index.ts
- yarn.lock
**Problem:** Reading GH action logs is hard, even with our nice output. Figuring out eslint errors could be easier.
**Solution:** Add file annotations via a custom formatter
> feat(eslint): add github annotations

- .changeset/mighty-pots-smash.md
- .changeset/nervous-ties-matter.md
- .changeset/smooth-hats-shop.md
- .changeset/sour-walls-remember.md
- .changeset/weak-students-stare.md
- modules/core/src/core/graph/commands/__tests__/verify.test.ts
- modules/core/src/core/graph/commands/verify.ts
- modules/core/src/core/install/commands/__tests__/install.test.ts
- modules/core/src/core/install/commands/install.ts
- modules/core/src/core/tasks/commands/__tests__/tasks.test.ts
- modules/core/src/core/tasks/commands/tasks.ts
- modules/logger/src/LogStep.ts
- modules/logger/src/Logger.ts
- modules/logger/src/__tests__/LogStep.test.ts
- modules/logger/src/index.ts
- modules/test-cli/src/index.ts
- plugins/changesets/src/commands/__tests__/add.test.ts
- plugins/changesets/src/commands/__tests__/prerelease.test.ts
- plugins/changesets/src/commands/__tests__/publish.test.ts
- plugins/changesets/src/commands/__tests__/version.test.ts
- plugins/changesets/src/commands/publish.ts
- plugins/eslint/src/commands/__tests__/eslint.test.ts
- plugins/prettier/src/commands/__tests__/prettier.test.ts
- plugins/prettier/src/commands/prettier.ts
**Problem:** Getting logger output in tests (whether resolving or rejecting) is difficult because we rely on `process.stderr` to write logs.
**Solution:** Switch `Logger` and `LogStep` to use dependency injection for the stream to write to. Update `@onerepo/test-cli` to pass in a stream that captures the output and resolve/reject the output accordingly.
> refactor(logger): allow dependency-injection of writable to logger

- .changeset/brave-bikes-buy.md
- .changeset/purple-tomatoes-travel.md
- .changeset/silly-wasps-clap.md
- bin/one.cjs
- commands/build.ts
- docs/commands/typedoc.ts
- docs/src/components/Sidebar.astro
- docs/src/pages/docs/telemetry.md
- modules/core/src/__tests__/index.test.ts
- modules/core/src/__tests__/performance.test.ts
- modules/core/src/index.ts
- modules/core/src/performance.ts
- modules/core/src/types.ts
- modules/logger/src/LogStep.ts
- modules/logger/src/Logger.ts
- modules/logger/src/__tests__/LogStep.test.ts
- modules/logger/src/__tests__/Logger.test.ts
- modules/package-manager/src/methods.ts
- modules/subprocess/src/index.ts
- modules/yargs/src/yargs.ts
**Problem:** Performance marks and measurements are a little ad-hoc at the moment
**Solution:** Internally, only use marks with `onerepo_start_` and `onerepo_end_` prefixes. This allows creating measurements from start to end marks more reliably.
- Passes the parsed `argv` to every measurement
- Merges mark details
> refactor: performance logging

- .changeset/swift-suns-tell.md
- modules/builders/src/__tests__/getters.test.ts
- modules/builders/src/getters.ts
- modules/subprocess/src/index.ts
- modules/yargs/src/yargs.ts
**Problem:** When running `one eslint` by default on changes with many affected files, some obscure and unexplainable errors will be thrown.
Likely due to the number of files hitting a system limit of the number of characters a subprocess can receive as arguments, eslint gets confused with partial/broken paths and will error out.
**Solution:** Have `getFilepaths` include an `affectedThreshold`. Starting with an arbitrary number of 100 files and will consider tuning that as necessary in the future.
> feat(builders): limit getFilepaths with a threshold

- .changeset/wild-otters-shout.md
- modules/core/src/core/install/commands/__tests__/install.test.ts
- modules/core/src/core/install/commands/install.ts
- modules/core/src/core/tasks/commands/__tests__/tasks.test.ts
- modules/core/src/index.ts
- modules/logger/src/LogStep.ts
- modules/logger/src/Logger.ts
- modules/logger/src/__tests__/Logger.test.ts
- modules/logger/src/index.ts
- modules/subprocess/src/index.ts
- modules/test-cli/src/index.ts
- modules/yargs/src/middleware/environment.ts
- modules/yargs/src/middleware/sudo-check.ts
- modules/yargs/src/yargs.ts
**Problem:** The logger was leaving behind open file descriptors, preventing node from exiting cleanly without explicitly calling `process.exit()`
**Solution:** This was on the list anyway… Removes the `logger` singleton in favor of a getter method, `getLogger()` that more strictly sets the singleton to the global object. On teardown, we explicitly call the internal method `destroyLogger()`
> fix(logger): ensure logger is created/destroyed properly

- .changeset/flat-boxes-allow.md
- commands/build.ts
This is the rogue package that _must_ be built & published as commonjs, because ESLint only uses commonjs.
Fixes build to check for package.json "type" field and uses that
> fix(eslint-formatter): fix build

- .changeset/thin-panthers-destroy.md
- plugins/eslint/src/commands/__tests__/eslint.test.ts
- plugins/eslint/src/commands/eslint.ts
**Problem:** If an eslint configuration has a problem (eg, missing referenced plugin), eslint will respond with no stdout, but some stderr.
**Solution:** Ensure that's watched for, caught, and reported as an error.
> fix(eslint): fail when eslint reports stderr

- .changeset/early-pandas-push.md
- modules/package-manager/src/__tests__/npm.test.ts
- modules/package-manager/src/__tests__/pnpm.test.ts
- modules/package-manager/src/__tests__/yarn.test.ts
- modules/package-manager/src/npm.ts
- modules/package-manager/src/pnpm.ts
- modules/package-manager/src/yarn.ts
**Problem:** Seeing reports of some registries (nexus in particular) responding with no output when getting package info (npm info/yarn npm info) to determine publishable modules.
**Solution:** Assume this means the package might need publishing. NOTE: this is not really correct to assume, but the only other options would be to continue requesting info until it comes back clean, which is not exactly great either.
> fix(package-manager): recover from json parsing in publishable check

- .changeset/new-chicken-wink.md
- commands/__tests__/__fixtures__/build/modules/burritos/package.json
- commands/__tests__/__fixtures__/build/modules/churros/package.json
- commands/__tests__/__fixtures__/build/modules/tacos/package.json
- commands/__tests__/build.test.ts
- modules/core/src/core/tasks/README.md
- modules/core/src/core/tasks/commands/__tests__/__fixtures__/repo/onerepo.config.js
- modules/core/src/core/tasks/commands/__tests__/tasks.test.ts
- modules/core/src/core/tasks/commands/tasks.ts
- modules/graph/src/Workspace.ts
**Problem:** Since the inclusion of true sequential tasks, the auto `pre-` and `post-` prefixing for task lifecycles has been unnecessary and generally discouraged. There are no strong arguments for being able to run explicit `pre-` and `post-` lifecycles separately, when they are also automatically run with the non-prefixed (eg `pre-commit`, `commit`, `post-commit` would be run automatically for `--lifecycle=commit`). This was also poorly documented and difficult to explain.
**Solution:** Drop the code for this entirely. Reduce the included lifecycles.
> refactor(core): remove implied pre- and post- lifecycles

- .changeset/unlucky-seahorses-confess.md
- modules/file/src/index.ts
**Problem:**
When using Prettier v2, file formatting was broken due to support for Prettier v3, which was rewritten to use ESM exports instead of CJS `defaults`.
**Solution:**
if `default` in the prettier import, use that, otherwise continue to use the v3 api
> fix(file): fix default export for prettier 2 in format

- .changeset/sharp-shirts-eat.md
- modules/core/src/core/tasks/commands/__tests__/__fixtures__/repo/onerepo.config.js
- modules/core/src/core/tasks/commands/__tests__/tasks.test.ts
- modules/core/src/core/tasks/commands/tasks.ts
**Problem:**
Sequential tasks are not being included from the root workspace when non-root workspace changes are made.
**Solution:**
When determining `force` adding tasks from the root, ensure checking `Array.isArray`, not just if task is `string`
> fix(core): sequential tasks at root need to be force-included

- .changeset/chilled-zebras-serve.md
- .changeset/empty-wasps-jog.md
- .changeset/nervous-goats-cheat.md
- .changeset/silent-pianos-double.md
- docs/commands/start.ts
- docs/src/content/docs/custom-commands.md
- modules/core/src/core/install/commands/__tests__/install.test.ts
- modules/core/src/core/install/commands/install.ts
- modules/package-manager/src/methods.ts
- modules/package-manager/src/npm.ts
- modules/package-manager/src/pnpm.ts
- modules/package-manager/src/yarn.ts
- modules/subprocess/src/index.ts
- plugins/changesets/src/commands/__tests__/init.test.ts
- plugins/changesets/src/commands/init.ts
- plugins/eslint/src/commands/__tests__/eslint.test.ts
- plugins/eslint/src/commands/eslint.ts
- plugins/prettier/src/commands/__tests__/prettier.test.ts
- plugins/prettier/src/commands/prettier.ts
- plugins/typescript/src/commands/__tests__/typescript.test.ts
- plugins/typescript/src/commands/typescript.ts
- plugins/vitest/src/commands/__tests__/vitest.test.ts
- plugins/vitest/src/commands/vitest.ts
Adds `packageManager.run` an `packageManager.batch` – helpers for running `npx`/`npm exec` like commands using the correct package manager an avoiding needing to look up the location of the installed `.bin/*` file(s)
> feat(package-manager): run and batch using npm exec-like methods

- .changeset/modern-sheep-attend.md
- .changeset/orange-moose-greet.md
- .changeset/pink-papayas-unite.md
- docs/src/content/docs/custom-commands.md
- modules/core/src/index.ts
- modules/file/src/index.ts
- modules/logger/src/LogStep.ts
- modules/logger/src/Logger.ts
- modules/logger/src/__tests__/Logger.test.ts
- modules/subprocess/src/index.ts
- plugins/changesets/src/commands/prerelease.ts
- plugins/changesets/src/commands/publish.ts
**Problem:**
We now have a handy `logger.info` method for presenting important information that users probably need.
**Solution:**
Make use of it where it makes sense. Update documentation.
> refactor: make use of logger.info

- .changeset/weak-dancers-chew.md
- bin/one.cjs
- modules/core/src/core/docgen/index.ts
- modules/core/src/core/generate/index.ts
- modules/core/src/core/graph/index.ts
**Problem:**
When using worktrees, files are not generated in the worktree, but the repo root instead.
**Solution:**
Also relates to graph customSchema & potentially docgen outFile – allowing these paths to be absolute will result in the the original repo root paths be used and not be resolved from the worktree.
This updates the setup and configuration requirements to fix this issue, throwing an error if configured incorrectly using absolute paths.
Fixes #448
> fix(core): require core path config options be relative to the root

- .changeset/poor-months-try.md
- modules/core/src/core/docgen/index.ts
- modules/core/src/core/docgen/yargs.ts
**Problem:**
Some yargs methods are left unimplemented. This can cause `docgen` to fail.
**Solution:**
Instead of hard failing, log a warning and return the yargs instance so that the doc generation can continue on. This is accomplished by using a Proxy object in the constructor to automatically handle everything.
> refactor(core): warn on unimplemented yargs methods

- modules/core/src/core/install/commands/__tests__/install.test.ts
- modules/core/src/core/install/commands/install.ts
- modules/test-cli/src/index.ts
**Problem:**
When installing the onerepo cli, if the user installs while under a path that includes spaces the installation fails to escape the spaces breaking the command 
**Solution:**
Escape any spaces in the installation path during install
> fix: escape spaces in onerepo cli installation path

- .changeset/hip-rockets-retire.md
- .changeset/orange-books-study.md
- modules/core/package.json
- modules/test-cli/package.json
- modules/test-cli/src/index.ts
- plugins/jest/package.json
- plugins/vitest/package.json
- yarn.lock
**Problem:**
When attempting to run a test with something like `run('-w "foo bar"')`, the argument parser in tests was resulting in arguments `{ _: ['bar'], 'w': 'foo' }`, but we expect it to be `{ _: [], 'w': 'foo bar' }`
**Solution:**
There was a `parse` + `unparse` step within the `builder` for the test-cli, likely existed for some historical reasons that are no longer relevant. This removes them.
Also sneaking in a fix for missing semver dependency.
> fix(test-cli): remove unnecessary parse/unparse steps in test builder

- modules/logger/src/LogStep.ts
- modules/logger/src/Logger.ts
- modules/logger/src/__tests__/LogStep.test.ts
- modules/logger/src/__tests__/Logger.test.ts
- modules/logger/src/index.ts
**Problem:**
When using `bufferSubLogger` (like with `tasks`), only errors are buffered through.
**Solution:**
Add `.hasWarning`, `.hasInfo`, `.hasLog` to `LogStep` and `Logger`, check those and verbosity and pass through accordingly.
Removes `onError` from `LogStep` as that's not really necessary anymore.
> feat(logger): add all log passthroughs for bufferSubLogger

- .changeset/young-roses-divide.md
- .husky/pre-commit
- docs/.eslintrc.cjs
- modules/builders/src/getters.ts
- modules/core/src/core/tasks/README.md
- modules/core/src/core/tasks/commands/tasks.ts
- modules/core/src/core/tasks/index.ts
- modules/git/src/index.ts
- onerepo.config.js
**Problem:**
You may only want to run some commands against `--staged` files, which is an option on `getAffected`. However, `getWorkspaces` does not respect nor pass this flag along through when getting affected files.
**Solution:**
Ensure `getWorkspaces()` passes the `staged` option through.
> fix: ensure getWorkspaces respects --staged flag

- modules/logger/src/LogStep.ts
**Problem:**
With multiple loggers, sometimes `Completed` timing is coming out as 0ms because the start/end marks are not found.
**Solution:**
If a logger/logstep doesn't have a name, create a `#startMark` using high resolution time. 
Alternative thought: could generate a unique hash, but that's more expensive…
> fix(logger): start/end timing for multiple loggers

- .changeset/orange-cups-nail.md
- modules/git/src/workflow.ts
If a repo has a long running post-checkout hook, the staging piece of the git workflow during `one tasks -c pre-commit` will end up taking a bunch of time that we really don't want to wait for. It should be safe to skip these hooks.
> fix(git): skip HUSKY during git checkout

- .changeset/proud-apes-brush.md
- modules/git/src/workflow.ts
**Problem:**
HUSKY doesn't necessarily account for all of the ways that git hooks can be configured.
**Solution:**
Use `git -c core.hooksPath=/dev/null` when wanting to skip hooks.
> fix(git): skip git hooks via config param

- .changeset/thin-plums-accept.md
- plugins/typescript/src/commands/__tests__/typescript.test.ts
- plugins/typescript/src/commands/typescript.ts
(nb: copied from #506)
**Problem:**
Non project reference enabled project started erroring during `tsc` with this error message
>    │ ERR error TS5093: Compiler option '--verbose' may only be used with '--build'.
**Solultion:**
Remove `--verbosity` flag from `tsc` when running on non project reference enabled workspaces
> fix: remove verbosity on non project ref tsc runs

- .changeset/tough-news-allow.md
- modules/package-manager/src/__tests__/get-package-manager.test.ts
- modules/package-manager/src/get-package-manager.ts
**Problem:**
Not really a problem, but determining the package manager through file lookups takes extra processing.
**Solution:**
If it is set, use the environment variable `npm_config_user_agent`
> perf(package-manager): use npm_config_user_agent env var

- .changeset/weak-pumpkins-kick.md
- plugins/prettier/src/commands/__tests__/prettier.test.ts
- plugins/prettier/src/commands/prettier.ts
- plugins/prettier/src/index.ts
**Problem:**
Prettier can be slow when there are many files (particularly with large repos and running with `--all`).
**Solution:**
Enable Prettier' cache by default.
> pref(prettier): enable prettier cache

- modules/create/src/index.ts
- modules/onerepo/src/setup/setup.ts
- modules/test-cli/src/index.ts
- modules/yargs/package.json
- modules/yargs/src/middleware/engine-check.ts
- modules/yargs/src/middleware/index.ts
- modules/yargs/src/middleware/sudo-check.ts
- modules/yargs/src/yargs.ts
- package.json
- plugins/performance-writer/src/__tests__/index.test.ts
- yarn.lock
**Problem:**
In organizations where you may use multiple node versions due to legacy applications or don't have a distributed MDE, you might end up on the wrong node version, causing issues.
**Solution:**
We can build in a middleware check that can always run on every command to ensure the current engine matches that which is defined in the root package.json
> feat: add engines check

- .changeset/hungry-pugs-protect.md
- .github/workflows/pull-request.yaml
- docs/tailwind.config.ts
- modules/onerepo/src/core/tasks/README.md
- modules/onerepo/src/core/tasks/commands/__tests__/tasks.test.ts
- modules/onerepo/src/core/tasks/commands/tasks.ts
- modules/onerepo/vitest.config.js
**Problem:**
Current GH action strategy may not be best for all use cases. It can possibly overload systems and use too many action runners at once.
**Solution:**
Add a `--shard` argument to `tasks`.
> feat(tasks): add --shard

- bin/one.mjs
- docs/src/content/docs/core/tasks.mdx
- modules/github-action/src/get-tasks.ts
**Problem:**
This file was held on to during the transition from old setup method requiring a custom `bin` file to run the `one` CLI. It should no longer be necessary.
**Solution:**
Turns out that the file is still necessary.
- Adds a note relating why it's needed here, but not in consumer repositories.
- Updates some documentation
- Fixes actions to use regular ternary instead of nullish coalescing to ensure the correct bin is used.
n/a
**Checklist:**
> chore: cleanup bin references

- modules/logger/src/Logger.ts
- modules/logger/src/__tests__/Logger.test.ts
**Problem:**
The logger was never clearly logging `Completed with errors`, only `Completed`
**Solution:**
Proxy the `hasErrors` through to the `defaultLogger` when an error message is received in any step.
Fixes #565
**Checklist:**
> fix(logger): completed never logs 'with errors'

- modules/onerepo/src/core/install/__tests__/install.test.ts
- modules/onerepo/src/core/install/install.ts
**Problem:**
Install doesn't work after you've added `onerepo` as a dependency and try to run `npm exec one install`
**Solution:**
Fix the `bin` file lookup for copying the correct file to the `~/.onerepo` folder.
Fixes #
**Checklist:**
> fix(core): install bin search location

- .changeset/calm-goats-train.md
- .changeset/new-rockets-study.md
- docs/src/content/docs/api/index.md
- modules/graph/src/Graph.ts
- modules/graph/src/Workspace.ts
- modules/graph/src/__tests__/Workspace.test.ts
- modules/graph/src/index.ts
- modules/onerepo/src/core/create/create.ts
- modules/package-manager/src/methods.ts
- plugins/changesets/src/commands/prerelease.ts
- plugins/changesets/src/commands/publish.ts
- plugins/changesets/src/publish-config.ts
**Problem:**
- Looking toward #569, there is some custom core functionality that should be moved up.
- Source dependencies are a core part of the reasoning for oneRepo, and the `publishConfig` merging is a key piece of that puzzle.
**Solution:**
Moves `applyPublishConfig` out of `@onerepo/plugin-changesets` and into the Workspace as `get publishablePackageJson()`
Relates to #569 
**Checklist:**
> refactor(core changesets): move publishablePackageJson into Workspace

- .changeset/afraid-peas-kiss.md
- .changeset/gorgeous-cobras-rule.md
- docs/src/content/docs/core/codeowners.mdx
- docs/src/content/docs/core/dependencies.mdx
- docs/src/content/docs/core/generate.mdx
- docs/src/content/docs/core/graph.mdx
- docs/src/content/docs/core/hooks.mdx
- docs/src/content/docs/core/install.mdx
- docs/src/content/docs/core/tasks.mdx
- docs/src/content/docs/plugins/changesets.mdx
- docs/src/content/docs/plugins/docgen.mdx
- docs/src/content/docs/plugins/docgen/example.mdx
- docs/src/content/docs/plugins/eslint.mdx
- docs/src/content/docs/plugins/jest.mdx
- docs/src/content/docs/plugins/prettier.mdx
- docs/src/content/docs/plugins/typescript.mdx
- docs/src/content/docs/plugins/vitest.mdx
- plugins/docgen/src/markdown.ts
**Problem:**
> **Aliases:** `$0`
Is confusing.
**Solution:**
List the full command string required for aliases instead of just the individual command name.
| Before | After        |
| ------ | ------------ |
| `$0`   | `one change` |
Also only renders the "Required" column in the options/positional table when there are 1 or more required options. Does not include the column if not.
Fixes #585
**Checklist:**
> feat(docgen): clarify aliases, reduce table sizes

- .changeset/beige-buckets-explain.md
- .changeset/purple-candles-exist.md
- modules/onerepo/src/core/dependencies/__tests__/add.test.ts
- modules/onerepo/src/core/dependencies/add.ts
**Problem:**
```sh
one deps add -w root -d normalizr
```
results in the dependency being added to every workspace.
**Solution:**
- Stop using `getWorkspaces` when adding deps and manually look up the requested directly
- Bonus: prevent adding prod dependencies to the root workspace
**Checklist:**
> fix: prevent adding deps to all when only root requested

- .changeset/silent-flowers-clean.md
- docs/package.json
- docs/src/content/docs/api/namespaces/file.md
- modules/file/src/index.ts
- modules/file/src/utils/strip-json-comments.ts
- modules/onerepo/package.json
- modules/onerepo/src/core/create/create.ts
- modules/onerepo/src/core/graph/verify.ts
- yarn.lock
**Problem:**
[Prettier 3.2.0](https://prettier.io/blog/2024/01/12/3.2.0) added support for JSONC. This becomes problematic because it will start writing certain files (eg tsconfig.json) with trailing commas. This will break certain places that we're reading and parsing JSON files, like `one graph verify`.
**Solution:**
Pull in [strip-json-comments](https://github.com/sindresorhus/strip-json-comments/tree/main) with some modifications, because we _always_ want to strip trailing commas for the purpose of running `JSON.parse()`.
Add `file.readJSON()` with optional ability to specify `jsonc` and run the `stripJsonComments` function.
#595 
**Checklist:**
> feat(file): add readJson with jsonc support

- .changeset/wise-actors-sort.md
- docs/src/content/docs/api/index.md
- modules/builders/src/getters.ts
- modules/logger/src/LogStep.ts
- modules/logger/src/Logger.ts
- modules/logger/src/__tests__/LogStep.test.ts
- modules/logger/src/index.ts
- modules/onerepo/src/core/graph/show.ts
- modules/onerepo/src/core/workspace/passthrough.ts
- modules/subprocess/src/index.ts
- plugins/changesets/src/commands/prerelease.ts
- plugins/changesets/src/commands/publish.ts
- plugins/changesets/src/commands/version.ts
**Problem:**
Logging can be expensive. Often times we need to map & join large objects for logging, but don't necessarily have the verbosity high enough to even see the output. In that scenario, we have wasted CPU cycles looping over the object and building a string.
Over-simplified, something like this, using the default verbosity, will build up the string, but never write anywhere.
```ts
logger.debug(workspaces.map((ws) => `${ws.name}`).join('\n');
```
**Solution:**
If log methods receive a function, execute it if and only if the verbosity is high enough to expect the output:
```ts
logger.debug(() => workspaces.map((ws) => `${ws.name}`).join('\n'));
```
Fixes #588
> feat(logger): Execute zero-argument functions when logging

- .changeset/sweet-stingrays-report.md
- .gitignore
- modules/onerepo/src/bin/one.ts
- modules/onerepo/src/bin/utils/get-config.ts
- modules/onerepo/src/bin/utils/update-node-modules.ts
**Problem:**
One thing that comes up a bunch is needing to remember to run `npm install` periodically. If it's not done ahead of trying to run commands or work with code in the repo, developers can potentially receiving confusing errors, particularly coming from areas they haven't been working in.
**Solution:**
At the `one` level before setup, before even requiring the local `onerepo` package or any of its dependencies:
1. Ensure we are in a valid repo
2. Get the configuration and root of the repository
3. if in `CI` or `ONEREPO_USE_HOOKS="0"`, go to 9
4. Get the lockfile, if not exists, go to 9
5. get a hash of the lockfile's contents
6. check if the lockfile's content hash matches a cache from the last time we ran this (if it hasn't run, it does not match) if matches, go to 9
7. run …
> feat(core): auto install node_modules if necessary

- .changeset/green-planets-nail.md
- docs/src/content/docs/plugins/docgen/example.mdx
- docs/src/content/docs/plugins/jest.mdx
- docs/src/content/docs/plugins/vitest.mdx
- plugins/jest/src/commands/__tests__/jest.test.ts
- plugins/jest/src/commands/jest.ts
- plugins/jest/src/index.ts
- plugins/vitest/src/index.ts
**Problem:**
In a monorepo, there are a lot of instances where we will set up the plumbing for tests in every Workspace, but not have any yet for some. When this happens, you need to manually pass `--passWithNoTests` to Jest
> [!NOTE]
> This apparently is not the case for Vitest, which exposes `passWithNoTests` as a configuration option, not just a CLI flag. Jest, however, does not expose a config option.
**Solution:**
Default to send `--passWithNoTests` to Jest.
Fixes #549
**Checklist:**
> feat(plugin-jest): default --passWithNoTests

- .changeset/shy-dots-tap.md
- docs/commands/collect-content.ts
- docs/src/content/docs/core/graph.mdx
- docs/src/content/docs/core/tasks.mdx
- docs/src/content/docs/plugins/docgen.mdx
- docs/src/content/docs/plugins/docgen/example.mdx
- plugins/docgen/src/index.ts
**Problem:**
Some docs generated by `one docgen` are using the local repository's configuration, but we don't actually want that for our documentation.
**Solution:**
Add an advanced argument: `--use-defaults` that will use the oneRepo default config.
> feat(plugin-docgen): --use-defaults

- modules/onerepo/src/core/changes/__tests__/add.test.ts
- modules/onerepo/src/core/changes/__tests__/migrate.test.ts
- modules/onerepo/src/core/changes/add.ts
- modules/onerepo/src/core/changes/migrate.ts
**Problem:**
Some systems (eg, GitHub) do literal sorting on filenames, so `11-…` will come before `2-…`. This will make change entry files confusing.
**Solution:**
left-pad the filenames with zeroes so there are three digits.
> feat(changes): left-pad change files with zeros

- docs/src/content/docs/core/changes.mdx
- docs/src/content/docs/core/codeowners.mdx
- docs/src/content/docs/core/dependencies.mdx
- docs/src/content/docs/core/generate.mdx
- docs/src/content/docs/core/graph.mdx
- docs/src/content/docs/core/hooks.mdx
- docs/src/content/docs/core/install.mdx
- docs/src/content/docs/core/tasks.mdx
- docs/src/content/docs/plugins/changesets.mdx
- docs/src/content/docs/plugins/docgen.mdx
- docs/src/content/docs/plugins/docgen/example.mdx
- plugins/docgen/.changes/014-large-brooms-tease.md
- plugins/docgen/src/markdown.ts
- plugins/docgen/src/yargs.ts
**Problem:**
`--show-advanced` is showing in every command options table. It's annoying.
**Solution:**
Hide it and other globals except at the root command.
> feat(docgen): hide advanced/globals

- docs/src/content/docs/core/changes.mdx
- docs/src/content/docs/core/dependencies.mdx
- docs/src/content/docs/plugins/changesets.mdx
- docs/src/content/docs/plugins/docgen/example.mdx
- modules/onerepo/src/core/changes/__tests__/__fixtures__/with-entries/modules/private/package.json
- modules/onerepo/src/core/changes/__tests__/verify.test.ts
- modules/onerepo/src/core/changes/index.ts
- modules/onerepo/src/core/changes/verify.ts
- modules/onerepo/src/core/dependencies/add.ts
**Problem:**
Some workflows will benefit from enforcing change entries are always present along with changes.
**Solution:**
Add `one change verify` to ensure every modified public/publishable Workspace includes change entries.
Fixes #537
> feat(changes): add 'verify' command

- modules/onerepo/.changes/015-forty-chefs-tell.md
- modules/onerepo/src/bin/one.ts
- modules/onerepo/src/core/install/index.ts
**Problem:**
It would be great to ensure that the installed version of the oneRepo CLI is up to date and matches the version used in the monorepo.
**Solution:**
Give a warning when the versions mismatch.
```
┌ Version mismatch detected!
│ WRN ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
│ WRN Globally installed version of the oneRepo CLI (0.15.0)
│ WRN is older than the local version in this monorepo (0.16.0).
│ WRN
│ WRN For the optimal experience, update the global version by re-installing:
│ WRN ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
│ WRN
│ WRN   $ one install
│ WRN
│ WRN ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
└ ✔ 0ms
```
```
┌ Version mismatch detected!
│ WRN ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
│ WRN Globally installed …
```
> feat: warn on installed version mismatch

- modules/onerepo/.changes/019-crazy-hairs-ask.md
- modules/onerepo/src/core/changes/__tests__/verify.test.ts
- modules/onerepo/src/core/changes/verify.ts
**Problem:**
Trying to version packages, I got caught by `change verify` failing.
**Solution:**
Don't fail if only `CHANGELOG.md` or `CHANGELOG.md` AND `package.json` are the only modified files.
> fix(core): don't fail change verify when versioning

- docs/src/content/docs/api/index.md
- modules/onerepo/.changes/000-cyan-plants-greet.md
- modules/onerepo/.changes/001-major-zoos-wait.md
- modules/package-manager/.changes/000-major-zoos-wait.md
- modules/package-manager/package.json
- modules/package-manager/src/__tests__/npm.test.ts
- modules/package-manager/src/__tests__/pnpm.test.ts
- modules/package-manager/src/__tests__/yarn.test.ts
- modules/package-manager/src/methods.ts
- modules/package-manager/src/npm.ts
- modules/package-manager/src/pnpm.ts
- modules/package-manager/src/yarn.ts
- modules/subprocess/.changes/000-cyan-plants-greet.md
- modules/subprocess/src/index.ts
- yarn.lock
**Problem:**
Publishing a `v1.0.0-beta.0` exposed an issue where `one change publish` added the dist-tag `latest`, despite it being a `beta` release.
**Solution:**
Rework the package-manager `publish()` function to:
1. Require `workspaces`
2. Use each workspace's version to determine what the tag should be, falling back on `latest` or the input `tag` option.
Fixes #622 
**Checklist:**
> fix(package-manager): pre-release publish tags

- docs/src/content/docs/api/namespaces/git.md
- modules/git/.changes/000-honest-mice-deny.md
- modules/git/src/index.ts
- modules/onerepo/.changes/003-sad-ravens-sink.md
- modules/onerepo/.changes/004-huge-islands-stay.md
- modules/onerepo/src/setup/setup.ts
**Problem:**
Finding race conditions with `git add` causing problems with git and it leaving `.git/index.lock` around, needing to be manually deleted.
**Solution:**
Store any files added via `git.updateIndex()` to a global cache and then flush them automatically during command shutdown.
**Checklist:**
> fix: prevent .git/index.lock issues

- plugins/eslint/.changes/000-twelve-jokes-stare.md
- plugins/eslint/package.json
- plugins/eslint/src/commands/eslint.ts
- plugins/prettier/.changes/000-twelve-jokes-stare.md
- plugins/prettier/package.json
- plugins/prettier/src/commands/prettier.ts
- yarn.lock
**Problem:**
TIL there's a fairly lightweight package that follows the actual `gitignore` spec for filtering filepaths. 
**Solution:**
This will avoid potential errors in the very naïve approach previously used in the eslint and prettier plugins.
> fix: use ignore package for filtering against ignore files

- modules/logger/.changes/000-ready-phones-grab.md
- modules/logger/src/LogStep.ts
- modules/logger/src/__tests__/LogStep.test.ts
- modules/logger/src/index.ts
- modules/onerepo/.changes/001-ready-phones-grab.md
**Problem:**
Got a report on Discord with this error when getting lots of eslint output:
```
(node:30394) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added to [LogBuffer]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```
**Solution:**
Had always wanted to be using `pipe` for the `LogBuffer` internally, as it's faster and uses less memory. This should resolve those issues.
> fix(logger): use pipes instead of listeners

- docs/src/content/docs/core/changes.mdx
- docs/src/content/docs/plugins/docgen/example.mdx
- modules/onerepo/.changes/002-curvy-donkeys-cut.md
- modules/onerepo/src/core/changes/__tests__/show.test.ts
- modules/onerepo/src/core/changes/index.ts
- modules/onerepo/src/core/changes/show.ts
- modules/onerepo/src/core/changes/utils/changelog.ts
- modules/onerepo/src/core/changes/utils/get-versionable.ts
**Problem:**
While it's easy to inspect the files in the `.changes` folder(s), it would be more helpful to have a command that could list and preview the changes together, including dependencies that need versioning.
**Solution:**
Adds `one change show` to preview versions and changelogs. Minimal for now, ripe for making prettier.
Fixes #656
**Checklist:**
> feat(core): add `one change show`

- docs/src/content/docs/api/index.md
- modules/onerepo/.changes/003-witty-paws-shop.md
- modules/onerepo/.changes/004-good-roses-hide.md
- modules/onerepo/src/setup/setup.ts
- modules/yargs/.changes/000-good-roses-hide.md
- modules/yargs/src/yargs.ts
**Problem:**
When running `one change version` without customizing the config `changes` object:
```
TypeError: Cannot read properties of undefined (reading 'formatting')
```
**Solution:**
- Exposes the fully `resolvedConfig` (with `plugins`) back to `HandlerExtra`.
- Removes the `@internal` flag on the `config` key for `HandlerExtra` so that it's documented. We cannot remove it at this point, so might as well expose it.
Fixes #677
> fix(core): ensures full resolved config sent to handlerextra

- modules/onerepo/.changes/004-good-roses-hide.md
- modules/onerepo/.changes/005-common-cobras-invite.md
- modules/onerepo/.changes/006-soft-rules-report.md
- modules/onerepo/src/core/dependencies/__tests__/__fixtures__/regression-678/onerepo.config.js
- modules/onerepo/src/core/dependencies/__tests__/__fixtures__/regression-678/package.json
- modules/onerepo/src/core/dependencies/__tests__/__fixtures__/regression-678/packages/bar/package.json
- modules/onerepo/src/core/dependencies/__tests__/__fixtures__/regression-678/packages/foo/package.json
- modules/onerepo/src/core/dependencies/__tests__/__fixtures__/regression-682/onerepo.config.js
- modules/onerepo/src/core/dependencies/__tests__/__fixtures__/regression-682/package.json
- modules/onerepo/src/core/dependencies/__tests__/__fixtures__/regression-682/packages/bar/package.json
- modules/onerepo/src/core/dependencies/__tests__/__fixtures__/regression-682/packages/foo/package.json
- modules/onerepo/src/core/dependencies/__tests__/verify.test.ts
- modules/onerepo/src/core/dependencies/utils/verify-dependencies.ts
**Problem:**
1. Public packages were able to list private packages as production dependencies.
2. Local workspace dependencies were skipped on actual version verification – only the integrity of the same version across the dependency graph was being verified, but not the actual declared version.
**Solution:**
Added checks & regression tests
Fixes #678, #682
**Checklist:**
> fix(core): regressions in graph verify for public/private & local

- modules/onerepo/.changes/007-chatty-buttons-cheat.md
- modules/package-manager/.changes/000-chatty-buttons-cheat.md
- modules/package-manager/src/npm.ts
**Problem:**
Trying to run `one eslint` in an NPM repository fails:
```
DBG Resolved CLI arguments:
DBG {
DBG   "_": [
DBG     "lint"
DBG   ],
DBG   "all": true,
DBG   "verbosity": 4,
DBG   "dry-run": false,
DBG   "quiet": false,
DBG   "skip-engine-check": false,
DBG   "cache": true,
DBG   "fix": true,
DBG   "pretty": true,
DBG   "github-annotate": true,
DBG   "$0": "one"
DBG }
┌ Lint files
│ LOG Running: Lint …
│ DBG Running command:
│ DBG {
│ DBG   "name": "Lint …",
│ DBG   "cmd": "npm",
│ DBG   "args": [
│ DBG     "exec",
│ DBG     "eslint",
│ DBG     "--color",
│ DBG     "--format",
│ DBG     "onerepo",
│ DBG     "--cache",
│ DBG     "--cache-strategy=content",
│ DBG     "--fix",
│ DBG     "."
│ DBG   ],
│ DBG   "opts": {
│ DBG     "env": {
│ DBG …
```
> fix(package-manager): npm exec include --

- docs/src/content/docs/plugins/docgen/example.mdx
- docs/src/content/docs/plugins/eslint.mdx
- plugins/eslint/.changes/001-kind-otters-make.md
- plugins/eslint/src/commands/__tests__/eslint.test.ts
- plugins/eslint/src/commands/eslint.ts
- plugins/eslint/src/index.ts
**Problem:**
The `--quiet` flag on `one eslint` is conflicting with the global `--quiet` flag on the `one` CLI, which sets the logger into silent mode (no output). This will make eslint look like nothing is happening and potentially fail silently.
**Solution:**
Switch from `quiet` to `warnings`. This should increase clarity of the flag and avoid conflicts.
**This is a breaking change!**
Fixes #
**Checklist:**
> fix(eslint): rename quiet option to warnings

- modules/onerepo/.changes/002-pink-peaches-design.md
- modules/onerepo/src/bin/one.ts
**Problem:**
Startup/configuration errors are missing full stack traces. They aren't super clear that it's not really oneRepo's fault.
**Solution:**
Use `(e as Error)?.stack` if available.
**Checklist:**
> fix(onerepo): add stack trace to config/setup failure

- modules/package-manager/.changes/000-giant-waves-hope.md
- modules/package-manager/src/__tests__/npm.test.ts
- modules/package-manager/src/__tests__/pnpm.test.ts
- modules/package-manager/src/__tests__/yarn.test.ts
- modules/package-manager/src/pnpm.ts
**Problem:**
pnpm dedupe in `package-manager` failes:
```
ERR Error: spawn yapnpmrn ENOENT
```
Root cause: typo in the code for the dedupe command in pnpm
**Solution:**
1. Fix the typo
2. Reduce risk of similar bugs by switching to use a module-level constant for the command name as is done for yarn and npm.
Fixes #737 
Closes #739
**Checklist:**
> fix(package-manager): pnpm dedupe

- bin/one.mjs
- modules/file/.changes/001-moody-doodles-hear.md
- modules/file/package.json
- modules/file/src/index.ts
- modules/graph/.changes/001-moody-doodles-hear.md
- modules/graph/package.json
- modules/graph/src/Graph.ts
- modules/graph/src/Workspace.ts
- modules/graph/src/__tests__/Graph.test.ts
- modules/graph/src/index.ts
- modules/onerepo/.changes/001-moody-doodles-hear.md
- modules/onerepo/package.json
- modules/onerepo/src/bin/one.ts
- modules/onerepo/src/bin/utils/get-config.ts
- modules/onerepo/src/bin/utils/update-node-modules.ts
- modules/onerepo/src/core/generate/generate.ts
- modules/onerepo/src/core/graph/verify.ts
- modules/onerepo/src/core/tasks/run-tasks.ts
- modules/onerepo/src/core/tasks/tasks.ts
- modules/onerepo/src/setup/index.ts
- modules/onerepo/src/setup/setup.ts
- package.json
- plugins/docgen/.changes/001-moody-doodles-hear.md
- plugins/docgen/package.json
- plugins/docgen/src/yargs.ts
- plugins/eslint/.changes/001-moody-doodles-hear.md
- plugins/eslint/package.json
- yarn.lock
**Problem:**
Was looking at upgrading the ESLint plugin to v9, but it requires Jiti ^2 and will not work with TS eslint configs unless this is also upgraded.
**Solution:**
Upgrade Jiti
Replaces #752 
Fixes #
**Checklist:**
> chore: update jiti

- modules/file/.changes/003-dirty-waves-start.md
- modules/file/.changes/004-giant-eyes-tan.md
- modules/file/src/__tests__/index.test.ts
- modules/file/src/index.ts
**Problem:**
Trying to use `file.writeSafe()` and `file.readSafe()` on JS/TS files results in invalid syntax errors when writing.
**Solution:**
Add comment start/end styles for all JS/TS file extensions.
Also reduces unnecessary newlines when writing content.
**Checklist:**
> fix(file): JS/TS comment syntax & extra whitespace in read/writeSafe

- docs/src/content/docs/docs/commands.mdx
- internal/jest-config/src/index.js
- jest.config.js
- modules/onerepo/.changes/005-gentle-spies-own.md
- modules/onerepo/.changes/006-lazy-plants-happen.md
- modules/onerepo/package.json
- modules/test-cli/.changes/004-gentle-spies-own.md
- modules/test-cli/package.json
- plugins/jest/.changes/003-rare-webs-shop.md
- plugins/jest/jest.config.js
- plugins/jest/package.json
- plugins/jest/src/commands/__tests__/jest.test.ts
- plugins/jest/tsconfig.json
- plugins/jest/vitest.config.js
- yarn.lock
**Problem:**
Yargs 18 is available as an ESM-first package. This is a great stepping stone for us as we look toward the future of removing Jiti as a dependency for loading TypeScript files starting with Node 22's `--experimental-strip-types` support.
**Solution:**
Upgrade Yargs. This appears to work as a drop-in replacement with no real changes required on our end.
> feat(onerepo): upgrade yargs to v18
